ocoda/event-sourcing

.circleci/config.yml
pnpm-lock.yaml

Fixes running ther `ci` command to run linting and formatting checks

💚 fix running the linting and formatting command

---

.github/codecov.yml

Adds a configuration file for codecov

🔧 add code coverage configuration

---

renovate.json

Bundles and automerges some dependency types

🔧 finetune renovate settings to reduce noise

---

.github/workflows/ci-libraries.yml
docker-compose.yml
packages/integration/mongodb/lib/mongodb-event-store.ts
packages/integration/postgres/biome.json
packages/integration/postgres/index.d.ts
packages/integration/postgres/index.js
packages/integration/postgres/index.ts
packages/integration/postgres/jest.config.js
packages/integration/postgres/lib/index.ts
packages/integration/postgres/lib/interfaces/index.ts
packages/integration/postgres/lib/interfaces/postgres-event-entity.ts
packages/integration/postgres/lib/interfaces/postgres-event-store-config.ts
packages/integration/postgres/lib/interfaces/postgres-snapshot-entity.ts
packages/integration/postgres/lib/interfaces/postgres-snapshot-store-config.ts
packages/integration/postgres/lib/postgres-event-store.ts
packages/integration/postgres/lib/postgres-snapshot-store.ts
packages/integration/postgres/package.json
packages/integration/postgres/tests/unit/postgres.event-store.spec.ts
packages/integration/postgres/tests/unit/postgres.snapshot-store.spec.ts
packages/integration/postgres/tsconfig.build.json
packages/integration/postgres/tsconfig.json
packages/integration/postgres/turbo.json
pnpm-lock.yaml

- **:whale: add a postgres container**
- **:sparkles: add the base files for a postgres integration**
- **:sparkles: implement the postgres event-store**
- **:fire: remove obsolete injectable decorator**
- **:sparkles: implement the postgres snapshot-store**
This PR adds a Postgres integration for event- and snapshot stores.
Fixes #283
_Please delete options that are not relevant._
Tests were added

[283] Add a postgres integration

---

.github/workflows/ci-libraries.yml

This PR fixes the pipeline caching and renames the jobs

👷 fix CI pipeline caching

---

README.md

This PR switches the status badge source to the CI Libraries workflow status

📝 update status badge

---

packages/integration/dynamodb/lib/dynamodb.event-store.ts
packages/integration/dynamodb/lib/dynamodb.snapshot-store.ts
packages/integration/mariadb/lib/mariadb.snapshot-store.ts
packages/integration/mongodb/lib/interfaces/mongodb-event-entity.ts
packages/integration/mongodb/lib/interfaces/mongodb-snapshot-entity.ts
packages/integration/mongodb/lib/mongodb.event-store.ts
packages/integration/mongodb/lib/mongodb.snapshot-store.ts
packages/integration/mongodb/tests/unit/mongodb.event-store.spec.ts
packages/integration/mongodb/tests/unit/mongodb.snapshot-store.spec.ts
packages/integration/postgres/lib/postgres.event-store.ts
packages/integration/postgres/lib/postgres.snapshot-store.ts

This PR refactors the typings for integration queries and makes sure all integrations only fetch the fields they need.
Fixes #308

[308] Only select required fields

---

packages/config/typescript/base.json
packages/core/lib/decorators/aggregate.decorator.ts
packages/core/lib/decorators/command-handler.decorator.ts
packages/core/lib/decorators/event-handler.decorator.ts
packages/core/lib/decorators/event-publisher.decorator.ts
packages/core/lib/decorators/event-serializer.decorator.ts
packages/core/lib/decorators/event-sourcing-options.decorator.ts
packages/core/lib/decorators/event.decorator.ts
packages/core/lib/decorators/query-handler.decorator.ts
packages/core/lib/decorators/snapshot.decorator.ts
packages/core/lib/exceptions/domain/domain-error.ts
packages/core/lib/exceptions/domain/id-already-registered.error.ts
packages/core/lib/exceptions/domain/id-not-found.error.ts
packages/core/lib/exceptions/domain/invalid-id.error.ts
packages/core/lib/exceptions/integration/event-store-collection-creation.exception.ts
packages/core/lib/exceptions/integration/event-store-persistence.exception.ts
packages/core/lib/exceptions/integration/index.ts
packages/core/lib/exceptions/integration/snapshot-store-collection-creation.exception.ts
packages/core/lib/exceptions/integration/snapshot-store-persistence.exception.ts
packages/core/lib/integration/event-store/in-memory.event-store.ts
packages/core/lib/integration/snapshot-store/in-memory.snapshot-store.ts
packages/integration/dynamodb/lib/dynamodb.event-store.ts
packages/integration/dynamodb/lib/dynamodb.snapshot-store.ts
packages/integration/mariadb/lib/mariadb.event-store.ts
packages/integration/mariadb/lib/mariadb.snapshot-store.ts
packages/integration/mongodb/lib/mongodb.event-store.ts
packages/integration/mongodb/lib/mongodb.snapshot-store.ts
packages/integration/postgres/lib/postgres.event-store.ts
packages/integration/postgres/lib/postgres.snapshot-store.ts

- **📝 add JSDocs to the decorators**
- **🔧 don't delete comments in builds**
- **📝 add JSDocs to the domain errors**
- **📝 add JSDocs to the integration errors**
- **🥅 catch and rethrow errors when creating event- and snapshot-collections**
This PR adds some inline documentation
Fixes #310

[310] Add some inline documentation

---

.github/workflows/cd-docs.yml

Refactors the docs deploy pipeline
Fixes #312

[312] Refactor the docs deploy pipeline

---

.github/workflows/cd-docs.yml

Adds a .nojekyll file to the dist folder
Fixes #312

[312] Refactor the docs CD pipeline

---

.github/labeler.yml
.github/workflows/cd-docs.yml
.github/workflows/ci-docs.yml
.github/workflows/ci-libraries.yml
.github/workflows/merge-check.yml
docs/next.config.js
docs/package.json

- **:fire: remove the .nojekyll file**
- **👷 re-add the .nojekyll file in the docs public directory**
- **👷 setup the ci workflow for the docs**
- **👷 prefix the asset paths on the GH pages build**
- moves the .nojekyll file
- improved the docs ci workflow
- fixes the docs build for gh-pages
Fixes #312

[312] Deploy the documentation

---

.github/workflows/cd-docs.yml
.github/workflows/ci-docs.yml
.github/workflows/ci-libraries.yml
.github/workflows/ci-other.yml
docs/next.config.js

Fixes the build for GH pages by setting the basePath and assetPrefix in the NextJS config.
Fixes #312

[312] Fix build for github pages

---

docs/next.config.js

This PR fixes the GITHUB_PAGES check
Fixes #312

[312] Fix the GITHUB_PAGES check

---

biome.json
docs/biome.json
docs/pages/advanced/multitenancy.mdx
docs/pages/start/aggregates.mdx
docs/pages/start/commands.mdx
docs/pages/start/install.mdx
docs/pages/start/repositories.mdx
docs/pages/start/value_objects.mdx
docs/pages/under_the_hood/streams.mdx

This PR improves syntax highlighting for the code blocks in the documentation.

📝 add better syntax highlighting to docs

---

packages/integration/dynamodb/lib/dynamodb.event-store.ts
packages/integration/dynamodb/lib/dynamodb.snapshot-store.ts

Fix DynamoDB serialization
Fixes #337

[337] Fix DynamoDB serialization

---

.github/workflows/benchmark.yml
.gitignore
benchmarks/benchmark.js

Fixes the benchmark pipeline
Fixes #335

[335] Fix benchmark pipeline

---

.github/workflows/benchmark.yml

Fixes the report filename to be used as a step summary
Fixes #335

[335] Fix report filename

---

.github/workflows/benchmark.yml

- **👷 fix the report folder**
- **👷 instead of reporting the job summary**

[355] Fix benchmark pipeline

---

.github/workflows/benchmark.yml

Fixes the path to upload the benchmark reports from
Fixes #335

[335] Fix benchmark upload path

---

.github/workflows/benchmark.yml

Fixes the reporting of the benchmark results
Fixes #335

[335] Fix reporting benchmark results

---

example/src/application/exceptions/domain-http-exceptions.ts
example/src/application/exceptions/exception.filter.ts
example/src/domain/exceptions/account-not-found.exception.ts
example/src/domain/exceptions/cannot-close-account.exception.ts
example/src/domain/exceptions/insufficient-funds.exception.ts
packages/core/lib/decorators/aggregate.decorator.ts
packages/core/lib/decorators/event.decorator.ts
packages/core/lib/exceptions/application/invalid-aggregate-stream-name.exception.ts
packages/core/lib/exceptions/application/invalid-event-stream-name.exception.ts
packages/core/lib/exceptions/domain/domain-error.ts
packages/core/lib/exceptions/domain/id-already-registered.error.ts
packages/core/lib/exceptions/domain/id-not-found.error.ts
packages/core/lib/exceptions/domain/invalid-id.error.ts
packages/core/lib/models/id.ts
packages/core/lib/models/uuid.ts
packages/core/tests/unit/decorators/aggregate.decorator.spec.ts
packages/core/tests/unit/decorators/event.decorator.spec.ts
packages/core/tests/unit/event-map.spec.ts
packages/core/tests/unit/models/id.spec.ts
packages/core/tests/unit/models/uuid.spec.ts

Renames Errors to Exceptions
Fixes #352

[352] Rename Errors to Exceptions

---

.github/workflows/release.yml

Adds a release pipeline
Fixes #351

[351] Add a release pipeline

---

.github/workflows/release.yml

👷 fix the versioning command in the release pipeline

---

.github/workflows/release.yml

Fixes the permissions of the release pipeline

👷 fix the permissions of the release pipeline

---

.github/codecov.yml
.github/workflows/ci-libraries.yml
.gitignore
package.json
packages/config/jest/base.js
packages/core/.npmignore
packages/core/jest.config.js
packages/core/package.json
packages/core/turbo.json
packages/integration/dynamodb/.npmignore
packages/integration/dynamodb/jest.config.js
packages/integration/dynamodb/package.json
packages/integration/dynamodb/turbo.json
packages/integration/mariadb/.npmignore
packages/integration/mariadb/jest.config.js
packages/integration/mariadb/package.json
packages/integration/mariadb/turbo.json
packages/integration/mongodb/.npmignore
packages/integration/mongodb/jest.config.js
packages/integration/mongodb/package.json
packages/integration/mongodb/turbo.json
packages/integration/postgres/.npmignore
packages/integration/postgres/jest.config.js
packages/integration/postgres/package.json
packages/integration/postgres/turbo.json
pnpm-lock.yaml
turbo.json

- **👷 refactor test configuration to output coverage**
- **👷 upload code coverage**
- allows to create code coverage reports when running tests
- uploads code coverage to codecov
- removes the release-it package and settings

General CI improvements

---

docs/public/robots.txt
docs/public/sitemap-0.xml
docs/public/sitemap.xml

_Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change._
Fixes # (issue)
_Please delete options that are not relevant._
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

🔍️ add robots.txt and sitemap to the docs website

---

example/package.json
example/src/app.module.ts
example/src/domain/events/account-opened.event-serializer.ts
example/tsup.config.ts
example/turbo.json
package.json
packages/core/lib/decorators/event-serializer.decorator.ts
packages/core/lib/handlers.loader.ts
packages/core/lib/interfaces/module/event-sourcing-module-options.interface.ts
packages/core/tests/unit/decorators/event-serializer.decorator.spec.ts
packages/core/tests/unit/handlers.loader.spec.ts
pnpm-lock.yaml
turbo.json

Fixes an issue where the metadata of custom event-serializers wasn't read correctly, resulting in them not being registered.
**Fixes:** https://github.com/ocoda/event-sourcing/issues/417

417 eventserializer loading not working

---

.changeset/eighty-cycles-hang.md

🔖 add a changeset
